### ISSUE TITLE
Please add metadata to your color scheme file

### ISSUE THREAD

**Issue by wez** [Hiroya-W/wezterm-sequoia-theme#1]
If you add a metadata section to your theme, something like:

```toml
[metadata]
name = "Sequoia Moonlight"
author = "Michael Andreuzza and Hiroya-W"
origin_url = "https://github.com/Hiroya-W/wezterm-sequoia-theme"
```

then I can update wezterm's release automation to include your color scheme in wezterm and show it with attribution in the color scheme browsing section of wezterm's docs.  For an example, see:
https://wezfurlong.org/wezterm/colorschemes/s/index.html#shades-of-purple-base16

https://github.com/EdenEast/nightfox.nvim/blob/main/extra/carbonfox/nightfox_wezterm.toml#L1-L4 is an example of the nightfox color schemes that are synced into wezterm.  https://wezfurlong.org/wezterm/colorschemes/c/index.html#carbonfox is its page in the docs.
